---
  extends: airbnb-base
  env:
    node: true
    mocha: true
    es6: true
  parser: typescript-eslint-parser
  parserOptions:
    sourceType: module
    ecmaFeatures:
      modules: true
  rules:
    indent: 0
    comma-dangle: 0
    import/no-unresolved: 0
    import/extensions: 0
    semi:
      - 2
      - never
